# Generated by Django 4.1.3 on 2023-02-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
